### ISSUE TITLE
How to train models on the multi-GPUs?

### ISSUE THREAD

**Issue by zhangseammm** [fatPeter/mini-splatting#5]
Thanks for your inspiring works! I want to train the large scale datasets such as alameda, but it only run on the GPU0 and run out of memory. It did not use my GPU1.
How to change the code?
<img width="625" alt="Screenshot 2024-08-21 at 14 51 56" src="https://github.com/user-attachments/assets/afd7773c-8ff3-4f47-b6ed-9df20a34fd27">

**Comment by fatPeter** [comment]
Thank you for your interest.


* Similar to most GS-based implementations, this repository does not support multi-gpu training.

Some suggestions for the large scale datasets:

* Load all GT images as ```uint8``` (modify ./scene/cameras.py), or just load images in cpu with ```--data_device cpu```  and a down-scaled resolution with ```--resolution```.
* Tune order of spherical harmonics with ```--sh_degree```.
* For Mini-Splatting-D, tune the number of points for depth reinitialization with ```--num_depth```.
* For Mini-Splatting, tune the number of points for depth reinitialization with ```--num_depth```, and the maximum number of Gaussians during optimization with ```--num_max```.

By the way, we have successfully validated our Mini-Splatting on datasets with over 7000 images and millions of Gaussians on one RTX 3090 without additional modifications. We find that multi-gpu is only necessary for models with over 10 million Gaussians. Check out works, such as Grendel-GS (https://github.com/nyu-systems/Grendel-GS), for multi-gpu implementation if necessary.
