### ISSUE TITLE
TRAIN：Why can't you train? The results are as follows:

### ISSUE THREAD

**Issue by chenmaolin1** [fatPeter/mini-splatting#9]
python train.py -s room -m output -i images_2 --eval --imp_metric indoor
Optimizing output
Output folder: output [08/12 14:32:12]
Traceback (most recent call last):
  File "train.py", line 423, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args)
  File "train.py", line 54, in training
    scene = Scene(dataset, gaussians)
  File "/mini-splatting/scene/__init__.py", line 56, in __init__
    assert False, "Could not recognize scene type!"
AssertionError: Could not recognize scene type!

**Comment by fatPeter** [comment]
`--source_path / -s` indicates Path to the source directory containing a COLMAP or Synthetic NeRF data set.

For example, if your 360 dataset is saved as `/dataset/360_v2` and you aim to train the `room` scan:
```
python train.py -s /dataset/360_v2/room -m output -i images_2 --eval --imp_metric indoor
```

**Comment by chenmaolin1** [comment]
> `--source_path / -s` indicates Path to the source directory containing a COLMAP or Synthetic NeRF data set.
> 
> For example, if your 360 dataset is saved as `/dataset/360_v2` and you aim to train the `room` scan:
> 
> ```
> python train.py -s /dataset/360_v2/room -m output -i images_2 --eval --imp_metric indoor
> ```

thanks
